# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

# Build matrix
# Turn on vdiffr only on r release
matrix:
  include:
  - r: devel
  - r: release
    env: VDIFFR_RUN_TESTS=true
  - r: oldrel
  - r: 3.4
  - r: 3.3

# Environment variables set for all builds
env:
  global:
  # Don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false
  # Switch off vdiffr by default
  - VDIFFR_RUN_TESTS=false

after_success:
  - Rscript -e 'covr::codecov()'
